from typing import List, Optional, Tuple, Callable, Union, Sequence

from pylabrobot.resources.container import Container
from pylabrobot.resources.errors import ResourceNotFoundError
from pylabrobot.resources.liquid import Liquid
from pylabrobot.resources.well_container import WellContainer
import enum

class TubeBottomType(enum.Enum):
  """Enum for the type of bottom of a tube."""

  FLAT = "flat"
  U = "U"
  V = "V"
  UNKNOWN = "unknown"

class Tube(WellContainer, Container):
  """Tube container, like Eppendorf tubes.

  Note that in regular use these will be automatically generated by the
  :class:`pylabrobot.resources.TubeRack` class.
  """

  def __init__(
    self,
    name: str,
    size_x: float,
    size_y: float,
    size_z: float,
    max_volume: float,
    material_z_thickness: Optional[float] = None,
    category: str = "tube",
    model: Optional[str] = None,
    bottom_type: Union[TubeBottomType, str] = TubeBottomType.UNKNOWN,
    compute_volume_from_height: Optional[Callable[[float], float]] = None,
    compute_height_from_volume: Optional[Callable[[float], float]] = None,
  ):
    if isinstance(bottom_type, str):
      bottom_type = TubeBottomType(bottom_type)
    """Create a new tube.

    Args:
      name: Name of the tube.
      size_x: Size of the tube in the x direction.
      size_y: Size of the tube in the y direction.
      size_z: Size of the tube in the z direction.
      material_z_thickness: Tube base to cavity base.
      max_volume: Maximum volume of the tube.
      category: Category of the tube.
    """

    super().__init__(
      name=name,
      size_x=size_x,
      size_y=size_y,
      size_z=size_z,
      material_z_thickness=material_z_thickness,
      category=category,
      max_volume=max_volume,
      model=model,
      compute_volume_from_height=compute_volume_from_height,
      compute_height_from_volume=compute_height_from_volume,
    )
    self.bottom_type = bottom_type

    self.tracker.register_callback(self._state_updated)

  def serialize(self) -> dict:
    return {**super().serialize(), "max_volume": self.max_volume}

  def set_liquids(self, liquids: List[Tuple[Optional["Liquid"], float]]):
    """Set the liquids in the tube.

    (wraps :meth:`~.VolumeTracker.set_liquids`)

    Example:
      Set the liquids in a tube to 10 uL of water:

      >>> tube.set_liquids([(Liquid.WATER, 10)])
    """

    self.tracker.set_liquids(liquids)

  def get_well(self, identifier: Union[str, int, Tuple[int, int]]) -> "Tube":
    """Get the tube itself. Alias for get_tube, for duck-typing compatibility with Plate."""
    return self.get_tube(identifier)

  def get_tube(self, identifier: Union[str, int, Tuple[int, int]]) -> "Tube":
    """Get the tube itself, if the identifier is valid for a single-item rack."""
    if identifier in ("A1", 0, (0, 0)):
      return self
    raise ResourceNotFoundError(f"Tube {self.name} does not have an item with identifier '{identifier}'.")

  def get_tubes(self, identifier: Union[str, Sequence[int]]) -> List["Tube"]:
    """Get the tube itself as a list, if the identifier is valid for a single-item rack."""
    if (isinstance(identifier, str) and identifier == "A1") or \
       (isinstance(identifier, Sequence) and not isinstance(identifier, str) and len(identifier) == 1 and identifier[0] == 0):
      return [self]
    raise ResourceNotFoundError(f"Tube {self.name} does not have items with identifier '{identifier}'.")

  def __getitem__(self, identifier: Union[str, int, Tuple[int, int]]) -> "Tube":
    """Get the tube itself, if the identifier is valid for a single-item rack."""
    return self.get_tube(identifier)


  @property
  def num_items(self) -> int:
    return 1

  def get_all_items(self) -> List["Tube"]:
    return [self]

  def set_well_liquids(
    self,
    liquids: Union[
      List[List[Tuple[Optional["Liquid"], Union[int, float]]]],
      List[Tuple[Optional["Liquid"], Union[int, float]]],
      Tuple[Optional["Liquid"], Union[int, float]],
    ],
  ) -> None:
    """Update the liquid in the volume tracker for the tube.

    Behaves like :meth:`pylabrobot.resources.TubeRack.set_well_liquids` for a single tube.
    """

    if isinstance(liquids, tuple):
      liquids = [liquids]
    elif isinstance(liquids, list) and len(liquids) > 0 and isinstance(liquids[0], list):
      if len(liquids) == 1 and len(liquids[0]) == 1:
        liquids = liquids[0]
      else:
        raise ValueError("For a single tube, liquids must be a single item or a 1x1 list of lists.")

    if len(liquids) != 1:
      raise ValueError(
        f"Number of liquids ({len(liquids)}) does not match number of tubes (1) in Tube '{self.name}'."
      )

    self.set_liquids(liquids)

  def disable_volume_trackers(self) -> None:
    """Disable volume tracking for this tube."""
    self.tracker.disable()

  def enable_volume_trackers(self) -> None:
    """Enable volume tracking for this tube."""
    self.tracker.enable()